version: "3.7"
services:
  mcserver:
    image: itzg/minecraft-server:java17-alpine
    container_name: mcserver
    env_file: .env
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - "./data:/data"
      - "./modpack:/modpack"
      - "./config:/config"
      - "./datapacks.json:/datapacks.json"
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 1m
      retries: 20
