hash-format = "sha256"

[[files]]
file = "mods/carpet.pw.toml"
hash = "4a7dc34ea75dda18719bdcee7fdb23a48c53142b57df960ffffbca652fc6b95a"
metafile = true

[[files]]
file = "mods/chunk-pregenerator-fabric.pw.toml"
hash = "a2c081a9c021ec3887f4d0476ca06e0c038c4b04e5550ccaa4bcd28a4e451c17"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "4c71686503225e97812bb5bb0b0022ec5144b4936344c99f3b4d3edaaf16f755"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1d87f8c04eeed21a9544cfad7f64afee6de58b5249a70b0367ba8522273a4816"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "f2116bab9a54a2f4d95fd7bced75572d95de31cec9b630c6cdfca5cf9d7ff96a"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "e75515de6f60227e731affe8077018bd68d8556ebd62032a5e5bd5217b28d44f"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84f503cded48e09f4991f73d05b483113ca57b3689ecab09f4d29846b98bb9c1"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "7076f0236db7652d6653a24c5aa60a3e265a77a9c137d8ecac837143556fcb46"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "7b110f0f87bb5f21381cc9c2338be6689219a36ef13cb34c22e745df4e6afbff"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "1db39b02058416cfc63be3982ee3d9b2a1a77d22d6ae562c17787ca7e9bacb9a"
metafile = true

[[files]]
file = "mods/towns-and-towers-structure-add-on.pw.toml"
hash = "bec28a4b4000894bf171694664bcfd73fbd73610fdba7ce4e78826c251df5645"
metafile = true
